import React from "react";
import Container from '@material-ui/core/Container';


const ImprintView = () => (
  <Container maxWidth="sm">
        <h2 style={{boxSizing: 'border-box', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0.9rem 0px 0.45rem', padding: '0px', color: 'rgb(31, 130, 192)', fontWeight: 200, fontSize: '1.8rem', lineHeight: '2.2rem', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><span style={{fontSize: '36px'}}>Imprint</span></h2>
        <hr />
        <p><br /></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Die Institute</p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><br style={{boxSizing: 'inherit'}} /><b className="bold" style={{boxSizing: 'border-box', fontWeight: 400}}><strong>Fraunhofer-Institut für Intelligente Analyse- und Informationssysteme</strong></b><strong><br style={{boxSizing: 'inherit'}} />Schloss Birlinghoven<br style={{boxSizing: 'inherit'}} />53757 Sankt Augustin</strong></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><br /></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><b className="bold" style={{boxSizing: 'border-box', fontWeight: 400}}><strong>Fraunhofer-Institut für Verkehrs- und Infrastrutkursysteme IVI</strong></b><strong><br style={{boxSizing: 'inherit'}} />Zeunerstrasse 38</strong></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><strong>01069 Dresden<br style={{boxSizing: 'inherit'}} /></strong></p>
        <article style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><br /></article>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><b className="bold" style={{boxSizing: 'border-box', fontWeight: 400}}><strong>Fraunhofer-Institut für Software und Systemtechnik ISST</strong></b></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><b className="bold" style={{boxSizing: 'border-box', fontWeight: 400}}><strong>Emil-Frigge-Strasse 91</strong></b><strong><br style={{boxSizing: 'inherit'}} /></strong></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><strong>44227 Dortmund</strong></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>sind rechtlich nicht selbstständige Einrichtung der</p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Fraunhofer-Gesellschaft<br style={{boxSizing: 'border-box'}} />zur Förderung der angewandten Forschung e.V.<br style={{boxSizing: 'inherit'}} />Hansastraße 27 c<br style={{boxSizing: 'inherit'}} />80686 München<br style={{boxSizing: 'inherit'}} />Internet: <a className="external" href="http://www.fraunhofer.de/" style={{boxSizing: 'border-box', textDecoration: 'underline', backgroundColor: 'transparent', color: 'rgb(31, 130, 192)'}} target="_blank">www.fraunhofer.de</a><br style={{boxSizing: 'border-box'}} />E-Mail: info(at)zv.fraunhofer.de</p>
        <h4 style={{boxSizing: 'border-box', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0.9rem 0px 0.45rem', padding: '0px', color: 'rgb(31, 130, 192)', fontWeight: 200, fontSize: '1.8rem', lineHeight: '2.2rem', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Verantwortliche Redaktion:</h4>
        <hr />
        <p><br /></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><span className="linklist" style={{boxSizing: 'border-box', whiteSpace: 'inherit', fontSize: '1.2rem', lineHeight: '1.5rem', letterSpacing: '0.025em', fontWeight: 400, paddingLeft: '1.5rem'}}><a href="mailto:dennis.oliver.kubitza@iais.fraunhofer.de" style={{boxSizing: 'border-box', textDecoration: 'underline', backgroundColor: 'transparent', color: 'rgb(31, 130, 192)', whiteSpace: 'normal', overflowWrap: 'break-word', wordBreak: 'break-word', hyphens: 'auto', display: 'inline', fontSize: '1.2rem', fontWeight: 400, lineHeight: '1.5rem', letterSpacing: '0.025em'}}>Sebastian Bader</a> (Fuer die Domaine .iais.fraunhofer.de)</span></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><span className="linklist" style={{boxSizing: 'border-box', whiteSpace: 'inherit', fontSize: '1.2rem', lineHeight: '1.5rem', letterSpacing: '0.025em', fontWeight: 400, paddingLeft: '1.5rem'}}><a href="mailto:sebastian.lorenz@iais.fraunhofer.de" style={{boxSizing: 'border-box', textDecoration: 'underline', backgroundColor: 'transparent', color: 'rgb(31, 130, 192)', whiteSpace: 'normal', overflowWrap: 'break-word', wordBreak: 'break-word', hyphens: 'auto', display: 'inline', fontSize: '1.2rem', fontWeight: 400, lineHeight: '1.5rem', letterSpacing: '0.025em'}}>Sebastian Lorenz</a> (Fuer die Domaine mobilitydataspace.io)</span></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}><br /></p>
        <h4 style={{boxSizing: 'border-box', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0.9rem 0px 0.45rem', padding: '0px', color: 'rgb(31, 130, 192)', fontWeight: 200, fontSize: '1.8rem', lineHeight: '2.2rem', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Fraunhofer Gesellschaft</h4>
        <hr />
        <p><br /></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Umsatzsteuer-Identifikationsnummer gemäß § 27 a<br style={{boxSizing: 'border-box'}} />Umsatzsteuergesetz: DE 129515865</p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Registergericht<br style={{boxSizing: 'border-box'}} />Amtsgericht München<br style={{boxSizing: 'border-box'}} />Eingetragener Verein<br style={{boxSizing: 'inherit'}} />Register-Nr. VR 4461</p>
        <h4 style={{boxSizing: 'border-box', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0.9rem 0px 0.45rem', padding: '0px', color: 'rgb(31, 130, 192)', fontWeight: 200, fontSize: '1.8rem', lineHeight: '2.2rem', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Vorstand</h4>
        <hr />
        <p><br /></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Prof. Dr.-Ing. Reimund Neugebauer, Präsident, Unternehmenspolitik und Forschung; kommissarische Leitung des Vorstandsbereichs ,&nbsp; Technologiemarketing und Geschäftsmodelle<br style={{boxSizing: 'inherit'}} />Prof. Dr. Alexander Kurz, Personal, Recht und Verwertung<br style={{boxSizing: 'inherit'}} />Dipl.-Kfm. Andreas Meuer,&nbsp;Finanzen und Digitalisierung</p>
        <h4 style={{boxSizing: 'border-box', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0.9rem 0px 0.45rem', padding: '0px', color: 'rgb(31, 130, 192)', fontWeight: 200, fontSize: '1.8rem', lineHeight: '2.2rem', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Nutzungsrechte</h4>
        <hr />
        <p><br /></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>© Fraunhofer-Gesellschaft e.V., München<br style={{boxSizing: 'border-box'}} /><br style={{boxSizing: 'border-box'}} />Alle Rechte vorbehalten.<br style={{boxSizing: 'inherit'}} />Die Urheberrechte dieser Webseite liegen vollständig bei der Fraunhofer-Gesellschaft.</p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Ein Download oder Ausdruck dieser Veröffentlichungen ist ausschließlich für den persönlichen Gebrauch gestattet. Alle darüber hinaus gehenden Verwendungen, insbesondere die kommerzielle Nutzung und Verbreitung, sind grundsätzlich nicht gestattet und bedürfen der schriftlichen Genehmigung.</p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Ein Download oder Ausdruck ist darüber hinaus lediglich zum Zweck der Berichterstattung über die Fraunhofer-Gesellschaft und ihrer Institute nach Maßgabe untenstehender Nutzungsbedingungen gestattet:</p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Grafische Veränderungen an Bildmotiven - außer zum Freistellen des Hauptmotivs - sind nicht gestattet. Es ist stets die Quellenangabe und Übersendung von zwei kostenlosen Belegexemplaren an die oben genannte Adresse erforderlich. Die Verwendung ist honorarfrei.</p>
        <h4 style={{boxSizing: 'border-box', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0.9rem 0px 0.45rem', padding: '0px', color: 'rgb(31, 130, 192)', fontWeight: 200, fontSize: '1.8rem', lineHeight: '2.2rem', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Haftungshinweis</h4>
        <hr />
        <p><br /></p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Wir übernehmen keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.</p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px 0px 1rem', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Wir sind bemüht, das Webangebot stets aktuell und inhaltlich richtig sowie vollständig anzubieten. Dennoch ist das Auftreten von Fehlern nicht völlig auszuschließen. Das Fraunhofer-Institut bzw. die Fraunhofer-Gesellschaft übernimmt keine Haftung für die Aktualität, die inhaltliche Richtigkeit sowie für die Vollständigkeit der in ihrem Webangebot eingestellten Informationen. Dies bezieht sich auf eventuelle Schäden materieller oder ideeller Art Dritter, die durch die Nutzung dieses Webangebotes verursacht wurden.</p>
        <p style={{boxSizing: 'border-box', fontSize: '14px', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', orphans: 2, textAlign: 'start', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px', WebkitTextStrokeWidth: '0px', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '0px', padding: '0px', lineHeight: '2.2rem', color: 'rgb(85, 85, 85)', fontFamily: 'FrutigerLTW02, "Helvetica Neue", Helvetica, Arial, sans-serif', fontWeight: 200, letterSpacing: 'normal', backgroundColor: 'rgb(255, 255, 255)'}}>Geschützte Marken und Namen, Bilder und Texte werden auf unseren Seiten in der Regel nicht als solche kenntlich gemacht. Das Fehlen einer solchen Kennzeichnung bedeutet jedoch nicht, dass es sich um einen freien Namen, ein freies Bild oder einen freien Text im Sinne des Markenzeichenrechts handelt.</p>
  </Container>

);

export default ImprintView;